config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
  	omniauth_callbacks: 'omniauth_callbacks'
  }

  root 'welcome#index'

  get 'twitter/search', to: 'twitter#search'
  get 'twitter/home_timeline', to: 'twitter#home_timeline'
  get 'twitter/following', to: 'twitter#following'
  get 'twitter/followers', to: 'twitter#followers'
  get 'twitter/favorites', to: 'twitter#favorites'
  get 'twitter/(:query)', to: 'twitter#search', as: 'twitter_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# :no-doc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter_client.rb
# :no-doc:
class TwitterClient
  def initialize(user = nil)
    @user = user
  end

  def native_client
    @native_client ||= Twitter::REST::Client.new do |config|
      config.consumer_key    = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret = Rails.application.secrets.twitter_consumer_secret

      if @user.present?
        config.access_token         = @user.token
        config.access_token_secret  = @user.secret
      end
    end
  end

  def home_timeline(uid)
    Rails.cache.fetch("home_timeline_for_#{uid}", expires_in: 5.minutes) do
      native_client.home_timeline
    end
  end

  def user_timeline(handle_or_uid, options)
    max_id = options[:max_id] || ''
    key = "user_timeline_for_#{handle_or_uid}#{max_id}"
    Rails.cache.fetch(key, expires_in: 5.minutes) do
      native_client.user_timeline(handle_or_uid, options)
    end
  end

  def following(uid)
    Rails.cache.fetch("following_for_#{uid}", expires_in: 5.minutes) do
      native_client.following
    end
  end

  def followers(uid)
    Rails.cache.fetch("followers_for_#{uid}", expires_in: 5.minutes) do
      native_client.followers
    end
  end

  def favorites(uid)
    Rails.cache.fetch("favorites_for_#{uid}", expires_in: 5.minutes) do
      native_client.favorites
    end
  end
end

app/models/user.rb
# :no-doc:
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable, :trackable
  devise :database_authenticatable,
         :registerable,
         :validatable

  devise :omniauthable, omniauth_providers: [:twitter]

  serialize :oauth_data, Hash

  class << self
    def find_or_create_from_twitter(oauth_data)
      User.where(
        provider: :twitter,
        uid: oauth_data['uid']
      ).first || User.create(
        provider: :twitter,
        uid: oauth_data['uid'],
        token: oauth_data['credentials']['token'],
        secret: oauth_data['credentials']['secret'],
        oauth_data: oauth_data
      )
    end
  end

  def email_required?
    provider.nil?
  end

  def password_required?
    provider.nil?
  end

  def twitter_client
    @twitter_client ||= TwitterClient.new(self)
  end

  def home_timeline
    twitter_client.home_timeline(uid)
  end

  def user_timeline
    twitter_client.user_timeline(uid)
  end

  def following
    twitter_client.following(uid)
  end

  def followers
    twitter_client.followers(uid)
  end

  def favorites
    twitter_client.favorites(uid)
  end
end

app/controllers/application_controller.rb
# :no-doc:
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/omniauth_callbacks_controller.rb
# :no-doc:
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!

  def twitter
    oauth_data = request.env['omniauth.auth']
    user = User.find_or_create_from_twitter(oauth_data)
    sign_in user
    redirect_to root_path, notice: 'Welcome Twitter User'
  end
end

app/controllers/twitter_controller.rb
# :no-doc:
class TwitterController < ApplicationController
  def search
    if params[:query].present?
      handle = params[:query]
      options = {}
      options[:count] = 25
      options[:max_id] = params[:max_id] if params[:max_id].present?
      @tweets = TwitterClient.new.user_timeline(handle, options)
    end
  end

  def home_timeline
    @tweets = current_user.home_timeline
  end

  def following
    @following = current_user.following
  end
  
  def followers
    @followers = current_user.followers
  end

  def favorites
    @tweets = current_user.favorites
  end  
end

app/controllers/welcome_controller.rb
# :no-doc:
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
  include Twitter::Autolink
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <div id="navbar" class="navbar-collapse collapse in" aria-expanded="true">
      <%= render 'layouts/navigation_links' %>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <% if current_user.token.present? %>
      <li><%= link_to('Feed', twitter_home_timeline_path) %></li>
      <li><%= link_to('Following', twitter_following_path) %></li>
      <li><%= link_to('Followers', twitter_followers_path) %></li>
      <li><%= link_to('Favorites', twitter_favorites_path) %></li>
    <% end %>

    <li><%= link_to('Search', twitter_search_path) %></li>
  </ul>

  <ul class="nav navbar-nav navbar-right" style="margin-right:0px;">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <%= current_user.email %>&nbsp;<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
      </ul>
    </li>
  </ul>
<% else %>
  <ul class="nav navbar-nav navbar-right" style="margin-right:15px;">
    <li>
      <%= link_to('SignUp', new_user_registration_path) %>
    </li>
    <li>
      <%= link_to('SignIn', new_user_session_path) %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TwitterOnRails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <div class="container-fluid">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/twitter/favorites.html.erb
<div class="row" style="margin-top:20px;">
  <div class="col-lg-12">
    <% if @tweets.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
          <th>Author</th>          
          <th>Tweet</th>
          <th>CreatedAt</th>
        </tr>
        </thead>

        <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.user.name %></td>
            <td><%= auto_link(tweet.text).html_safe %></td>
            <td><%= tweet.created_at %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no tweets for the search criteria.</p>
    <% end %>
  </div>
</div>

app/views/twitter/followers.html.erb
<div class="row" style="margin-top:20px;">
  <div class="col-lg-12">
    <% if @followers.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Statuses</th>
          <th>Followers</th>
          <th>Friends</th>
          <th>Favorites</th>
          <th>CreatedAt</th>
        </tr>
        </thead>

        <tbody>
        <% @followers.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.location %></td>
            <td><%= user.statuses_count %></td>
            <td><%= user.followers_count %></td>
            <td><%= user.friends_count %></td>
            <td><%= user.favorites_count %></td>
            <td><%= user.created_at %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no followers.</p>
    <% end %>
  </div>
</div>

app/views/twitter/following.html.erb
<div class="row" style="margin-top:20px;">
  <div class="col-lg-12">
    <% if @following.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Statuses</th>
          <th>Followers</th>
          <th>Friends</th>
          <th>Favorites</th>
          <th>CreatedAt</th>
        </tr>
        </thead>

        <tbody>
        <% @following.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.location %></td>
            <td><%= user.statuses_count %></td>
            <td><%= user.followers_count %></td>
            <td><%= user.friends_count %></td>
            <td><%= user.favorites_count %></td>
            <td><%= user.created_at %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no followings.</p>
    <% end %>
  </div>
</div>

app/views/twitter/home_timeline.html.erb
<div class="row" style="margin-top:20px;">
  <div class="col-lg-12">
    <% if @tweets.present? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
          <th>Author</th>          
          <th>Tweet</th>
          <th>CreatedAt</th>
        </tr>
        </thead>

        <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.user.name %></td>
            <td><%= auto_link(tweet.text).html_safe %></td>
            <td><%= tweet.created_at %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no tweets for the search criteria.</p>
    <% end %>
  </div>
</div>

app/views/twitter/search.html.erb
<div class="row" style="margin-top:20px;">
  <div class="col-lg-6">&nbsp;</div>
  <div class="col-lg-6">
    <%= form_tag twitter_index_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :query, params[:query], placeholder: "Search Tweets by handle", class: 'form-control' %>
        <span class="input-group-btn">
        <%= submit_tag "Search", class: 'btn btn-default' %>
      </span>
      </div>
    <% end %>
  </div>
</div>

<% if params[:query].present? %>
  <div class="row" style="margin-top:20px;">
    <div class="col-lg-12">
      <% if @tweets.present? %>
        <table class="table table-bordered table-striped table-hover" id="tweets">
          <thead>
          <tr>
            <th>ID</th>
            <th>Tweet</th>
            <th>CreatedAt</th>
          </tr>
          </thead>

          <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td><%= tweet.id %></td>
              <td><%= auto_link(tweet.text, username_url_base: "http://localhost:5000/twitter/").html_safe %></td>
              <td><%= tweet.created_at %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <%= link_to 'Next', twitter_index_path(query: params[:query], max_id: @tweets.last.id), class: 'btn btn-primary' %>

      <% else %>
        <p>There are no tweets for the search criteria.</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Tweets On Rails</h1>
<p>
  Twitter on Rails is a rails based application, by which you will be able to
  search for the tweets by a given search handle.
</p>